config/routes.rb
Rails.application.routes.draw do

    resources :relationships, only: [:create, :destroy]
    devise_for :users
    get 'settings' => 'twitter#settings', as: 'settings'
    get 'locale/:name' => 'twitter#locale', as: 'change_locale'
    get ':username/following' => 'twitter#following', as: 'following'
    get ':username/followers' => 'twitter#followers', as: 'followers'
    get ':username' => 'twitter#account', as: 'account'
    post '' => 'tweet#create'
    root to: 'twitter#index', as: 'tweets'
    match "*path", to: "application#catch_404", via: :all

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	validates :follower_id, :followed_id, presence: true
	belongs_to :follower, class_name: 'User'
	belongs_to :followed, class_name: 'User'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :user_id, :text, presence: true
    validates :text, length: { maximum: 140 }
    belongs_to :user

    def self.from_users_followed_by(user)
        followed_user_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
        where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", user_id: user.id)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
    has_many :tweets

    has_many :relationships, foreign_key: 'follower_id', dependent: :destroy
    has_many :followed_users, through: :relationships, source: :followed

    has_many :reverse_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
    has_many :followers, through: :reverse_relationships, source: :follower

    def following?(other_user)
        self.relationships.find_by(followed_id: other_user.id)
    end

    def follow!(other_user)
        self.relationships.create!(followed_id: other_user.id)
    end

    def unfollow!(other_user)
        self.relationships.find_by(followed_id: other_user.id).destroy!
    end

    def feed
        Tweet.from_users_followed_by(self)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_filter :set_locale
    protect_from_forgery with: :exception

    rescue_from ActionController::RoutingError, with: :render_not_found

    def catch_404
        raise ActionController::RoutingError.new(params[:path])
    end

    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
            devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
        end

    private
        def render_not_found
            render template: "layouts/403", status: 404
        end

        def set_locale
            session[:locale] == 'ru'  || session[:locale] == 'en' ? I18n.locale = session[:locale] : I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
            session[:locale] = I18n.locale
        end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :authenticate_user!
    before_action :get_users

    def create
        @user = User.find(params[:relationship][:followed_id])
        current_user.follow!(@user)
        current_user.update_attribute('followed_counter', current_user.followed_counter + 1)
        @user.update_attribute('followers_counter', @user.followers_counter + 1)
        @user = current_user
        respond_to do |format|
            format.js
        end
    end

    def destroy
        @user = Relationship.find(params[:id]).followed
        current_user.unfollow!(@user)
        current_user.update_attribute('followed_counter', current_user.followed_counter - 1)
        @user.update_attribute('followers_counter', @user.followers_counter - 1)
        @user = current_user
        respond_to do |format|
            format.js
        end
    end

    private
    def get_users
        @users = User.order(tweets_counter: :desc).limit(10)
    end
end

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
    before_action :authenticate_user!

    def create
        @tweet = Tweet.new(tweet_params)
        @tweet.user_id = current_user.id
        respond_to do |format|
            if @tweet.save
                @tweet.user.update_attribute('tweets_counter', @tweet.user.tweets_counter + 1)
                format.js
            else
                format.js
            end
        end
    end

    private
    def tweet_params
        params.require(:tweet).permit(:text, :user_id)
    end
end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController
    before_action :get_access, except: :locale
    before_action :get_users
    after_action :get_url, except: :locale

    def index
        @user = User.find(current_user.id)
        @tweets = Tweet.from_users_followed_by(@user).order(id: :desc)
        @tweet = Tweet.new
        render template: 'twitter/index'
    end

    def account
        @user = User.where('username = ?', params[:username]).first
        if @user
            @tweets = Tweet.where(user_id: @user).order(id: :desc)
            render template: 'twitter/account'
        else
            render template: "layouts/403", status: 404
        end
    end

    def following
        @user = params[:username] ? User.where('username = ?', params[:username]).first : User.find(current_user.id)
        if @user
            @following = @user.followed_users
            render template: 'twitter/following'
        else
            render template: "layouts/403", status: 404
        end
    end

    def followers
        @user = params[:username] ? User.where('username = ?', params[:username]).first : User.find(current_user.id)
        if @user
            @followers = @user.followers
            render template: 'twitter/followers'
        else
            render template: "layouts/403", status: 404
        end
    end

    def settings

    end

    def locale
        params[:name] == 'ru' ? session[:locale] = 'ru' : session[:locale] = 'en'
        redirect_to session[:url]
    end

    private
    def get_url
        session[:url] = request.original_url
    end

    def get_access
        render template: 'twitter/welcome' unless current_user
    end

    def get_users
        @users = User.order(tweets_counter: :desc).limit(10)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/layouts/403.html.slim
h2 ЗАПРОШЕННОЙ СТРАНИЦЫ НЕ СУЩЕСТВУЕТ

app/views/layouts/_menu.html.slim
nav.navbar.navbar-fixed-top role="navigation"
    /.navbar-header
        button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
    .pull-right
        = link_to 'ENG', change_locale_path('en'), class: 'btn btn-sm btn-primary'
        = link_to 'RUS', change_locale_path('ru'), class: 'btn btn-sm btn-primary'
        = link_to t('welcome.exit'), destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-danger', id: 'destroy'
    /.navbar-collapse.collapse
    ul.nav.navbar-nav
        li
            = link_to t('welcome.main'), tweets_path

app/views/layouts/application.html.slim
doctype html
html
    head
        title= "ZooTwitter | " + yield(:title)
        = stylesheet_link_tag    'application', media: 'all'
        = javascript_include_tag 'application'
        = csrf_meta_tags
    body
        = yield

app/views/relationships/create.js.erb
$('.user_block').html("<%= j render partial: 'twitter/users', object: @users, object: current_user %>");
$('.account_user').html("<%= j render partial: 'twitter/current', object: @user, object: current_user %>");

app/views/relationships/destroy.js.erb
$('.user_block').html("<%= j render partial: 'twitter/users', object: @users, object: current_user %>");
$('.account_user').html("<%= j render partial: 'twitter/current', object: @user, object: current_user %>");

app/views/tweet/_new.html.slim
.tweet
    p
        = image_tag 'avatar.jpg', class: 'img-responsive avatar_img', alt: 'avatar'
        = @tweet.user.username
        = link_to "@#{@tweet.user.username}", account_path(@tweet.user.username)
    p= @tweet.text

app/views/tweet/create.js.erb
$('#new_tweet').after("<%= j render(partial: 'tweet/new', object: @tweet) %>");
$('#tweet_text').val("");
$('#counter').html('140');
$('#add_tweet').addClass('disabled');
$('#no_tweets').remove();

app/views/twitter/_current.html.slim
.account
    .avatar
        = image_tag 'avatar.jpg', class: 'img-responsive big_avatar_img', alt: 'avatar'
    .account_links
        h3= link_to @user.username, account_path(@user.username)
        = link_to "@#{@user.username}", account_path(@user.username)
    .addition
        - if @user.id == current_user.id
            - link_to t('index.settings'), settings_path, class: 'btn btn-sm btn-default'
        - else
            - friends = Relationship.where(follower_id: current_user, followed_id: @user).first
            - if friends
                = simple_form_for current_user.relationships.find_by(followed_id: @user), html: { method: :delete }, remote: true do |f|
                    = f.button :submit, t('index.unfollow'), class: 'btn btn-sm btn-warning', disabled: 'disabled'
            - else
                = simple_form_for current_user.relationships.build(followed_id: @user.id), remote: true do |f|
                    = f.hidden_field :followed_id
                    = f.button :submit, t('index.follow'), class: 'btn btn-sm btn-primary', disabled: 'disabled'
    .account_info
        .tweet-count
            p.count= link_to t('welcome.count'), account_path(@user.username)
            p= @user.tweets_counter
        .tweet-count
            p.count= link_to t('welcome.followed'), following_path(@user.username)
            p= @user.followed_counter
        .tweet-count
            p.count= link_to t('welcome.followers'), followers_path(@user.username)
            p= @user.followers_counter

app/views/twitter/_users.html.slim
.users
    h4= t('index.main_users')
    - @users.each do |user|
        - if user.id != current_user.id
            .user
                p
                    = image_tag 'avatar.jpg', class: 'img-responsive avatar_img', alt: 'avatar'
                    = user.username
                    = link_to "@#{user.username}", account_path(user.username)
                    = " - #{user.tweets_counter}"
                    p
                        - friends = Relationship.where(follower_id: current_user, followed_id: user).first
                        - if friends
                            = simple_form_for current_user.relationships.find_by(followed_id: user), html: { method: :delete }, remote: true do |f|
                                = f.button :submit, t('index.unfollow'), class: 'btn btn-sm btn-warning'
                        - else
                            = simple_form_for current_user.relationships.build(followed_id: user.id), remote: true do |f|
                                = f.hidden_field :followed_id
                                = f.button :submit, t('index.follow'), class: 'btn btn-sm btn-primary'

app/views/twitter/account.html.slim
- provide(:title, 'Account')
= render 'layouts/menu'
#inside
    .container
        .row
            .col-xs-4.col-md-3
                .box
                    - if @user == current_user
                        .account_user= render 'twitter/current'
                    - else
                        = render 'twitter/current'
                .visible-xs.visible-sm.box
                    .user_block= render 'twitter/users'
            .col-xs-8.col-md-6#lenta
                - @tweets.each do |tweet|
                    .tweet
                        p
                            = image_tag 'avatar.jpg', class: 'img-responsive avatar_img', alt: 'avatar'
                            = tweet.user.username
                            = link_to "@#{tweet.user.username}", account_path(tweet.user.username)
                        p= tweet.text
                - if @tweets.length == 0
                    .tweet#no_tweets
                        p= t('index.no_tweets')
            .col-xs-4.col-md-3.visible-md.visible-lg.box
                .user_block= render 'twitter/users'

app/views/twitter/followers.html.slim
- provide(:title, 'Followers')
= render 'layouts/menu'
#inside
    .container
        .row
            .col-xs-12.col-md-3
                .box
                    - if @user == current_user
                        .account_user= render 'twitter/current'
                    - else
                        = render 'twitter/current'
                .box
                    .user_block= render 'twitter/users'
            .col-xs-12.col-md-9#following
                - if @followers.length == 0
                    p.no_one= t('index.followers')
                - @followers.each do |user|
                    .box.col-xs-4
                        .account
                            .avatar
                                = image_tag 'avatar.jpg', class: 'img-responsive big_avatar_img', alt: 'avatar'
                            .account_links
                                - if user != current_user
                                    - friends = Relationship.where(follower_id: current_user, followed_id: user).first
                                    - if friends
                                        = simple_form_for current_user.relationships.find_by(followed_id: user), html: { method: :delete }, remote: true do |f|
                                            = f.button :submit, t('index.unfollow'), class: 'btn btn-sm btn-warning', disabled: 'disabled'
                                    - else
                                        = simple_form_for current_user.relationships.build(followed_id: user), remote: true do |f|
                                            = f.hidden_field :followed_id
                                            = f.button :submit, t('index.follow'), class: 'btn btn-sm btn-primary', disabled: 'disabled'
                                - else
                                    = link_to t('index.settings'), settings_path, class: 'btn btn-sm btn-default'
                            .account_info
                                h3= link_to user.username, account_path(user.username)
                                p= link_to "@#{user.username}", account_path(user.username)

app/views/twitter/following.html.slim
- provide(:title, 'Following')
= render 'layouts/menu'
#inside
    .container
        .row
            .col-xs-12.col-md-3
                .box
                    - if @user == current_user
                        .account_user= render 'twitter/current'
                    - else
                        = render 'twitter/current'
                .box
                    .user_block= render 'twitter/users'
            .col-xs-12.col-md-9#following
                - if @following.length == 0
                    p.no_one= t('index.following')
                - @following.each do |user|
                    .box.col-xs-4
                        .account
                            .avatar
                                = image_tag 'avatar.jpg', class: 'img-responsive big_avatar_img', alt: 'avatar'
                            .account_links
                                - if user != current_user
                                    - friends = Relationship.where(follower_id: current_user, followed_id: user).first
                                    - if friends
                                        = simple_form_for current_user.relationships.find_by(followed_id: user), html: { method: :delete }, remote: true do |f|
                                            = f.button :submit, t('index.unfollow'), class: 'btn btn-sm btn-warning', disabled: 'disabled'
                                    - else
                                        = simple_form_for current_user.relationships.build(followed_id: user), remote: true do |f|
                                            = f.hidden_field :followed_id
                                            = f.button :submit, t('index.follow'), class: 'btn btn-sm btn-primary', disabled: 'disabled'
                                - else
                                    = link_to t('index.settings'), settings_path, class: 'btn btn-sm btn-default'
                            .account_info
                                h3= link_to user.username, account_path(user.username)
                                p= link_to "@#{user.username}", account_path(user.username)

app/views/twitter/index.html.slim
- provide(:title, 'Home')
= render 'layouts/menu'
#inside
    .container
        .row
            .col-xs-12.col-md-3
                .box
                    .account_user= render 'twitter/current'
                .visible-xs.visible-sm.box
                    .user_block= render 'twitter/users'
            .col-xs-12.col-md-6#lenta
                = simple_form_for @tweet, remote: true do |f|
                    = f.input :text, autofocus: true, label: false, id: 'tweet_text', input_html: { maxlength: 140 }, placeholder: t('index.tweet')
                    = f.button :submit, t('index.add'), class: 'btn btn-success disabled', id: 'add_tweet'
                    span#counter 140
                - @tweets.each do |tweet|
                    .tweet
                        p
                            = image_tag 'avatar.jpg', class: 'img-responsive avatar_img', alt: 'avatar'
                            = tweet.user.username
                            = link_to "@#{tweet.user.username}", account_path(tweet.user.username)
                        p= tweet.text
                - if @tweets.length == 0
                    .tweet#no_tweets
                        p= t('index.no_tweets')
            .col-xs-12.col-md-3.visible-md.visible-lg.box
                .user_block= render 'twitter/users'

app/views/twitter/welcome.html.slim
- provide(:title, 'Welcome')
.inside
    .shadow
.container
    .col-xs-12.col-sm-6.col-sm-offset-3.col-md-4.col-md-offset-8.block#login
        = simple_form_for(User.new, as: :user, url: session_path(:user)) do |f|
            .col-xs-12
                p= t('welcome.auth')
            .col-xs-12
                = f.input :username, autofocus: true, label: false
            .col-xs-8
                = f.input :password, autocomplete: 'off', label: false
            .col-xs-4
                = f.button :submit, t('welcome.enter'), class: 'btn btn-primary', id: 'authorization'
            .col-xs-12
                = f.input :remember_me, as: :boolean, label: t('welcome.remember')
    .col-xs-12.col-sm-6.col-sm-offset-3.col-md-4.col-md-offset-8.block#signup
        = simple_form_for(User.new, as: :user, url: registration_path(:user)) do |f|
            .col-xs-12
                p= t('welcome.reg')
            .col-xs-12
                = f.input :username, required: true, autofocus: true, label: false, placeholder: t('welcome.username')
            .col-xs-12
                = f.input :email, required: true, label: false, placeholder: t('welcome.email')
            .col-xs-12
                = f.input :password, required: true, label: false, placeholder: t('welcome.password')
            .col-xs-12
                = f.input :password_confirmation, autocomplete: 'off', required: true, label: false, placeholder: t('welcome.confirm')
            .col-xs-12.col-sm-5.col-sm-offset-7
                =  f.button :submit, t('welcome.reg'), class: 'btn btn-primary', id: 'registration'